[platformio]
src_dir = src
include_dir = include

[env]
platform = espressif32
framework = arduino
monitor_speed = 115200
lib_ldf_mode = deep+

lib_deps =
    WiFi
    mathieucarbou/ESPAsyncWebServer
    mathieucarbou/AsyncTCP

# Build flags
build_flags =
    -DMASK_VERSION=0x091A
    -DKNX_TUNNELING=10
    -DKNX_ROUTING
    -DKNX_BAUDRATE=38400
    -DNCN5120
    -I"/root/.platformio/packages/framework-arduinoespressif32/libraries/Network/src"

[env:tul_esp32c3]
board = seeed_xiao_esp32c3
build_flags = 
    ${env.build_flags}
    -I"/root/.platformio/packages/framework-arduinoespressif32-libs/esp32c3/include/esp_wifi/include"
    -DKNX_LED=4
    -DKNX_BUTTON=9
    -DKNX_SERIAL=Serial0
    -DKNX_RX_PIN=20
    -DKNX_TX_PIN=21

[env:tul32_esp32c6]
board = esp32-c6-devkitc-1
board_upload.flash_size = 4MB
board_build.partitions = partitions_4mb.csv
build_flags =
    ${env.build_flags}
    -I"/root/.platformio/packages/framework-arduinoespressif32-libs/esp32c6/include/esp_wifi/include"
    -DKNX_LED=8
    -DKNX_BUTTON=9
    -DKNX_SERIAL=Serial0
    -DKNX_RX_PIN=5
    -DKNX_TX_PIN=4
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
monitor_filters = esp32_exception_decoder
