#pragma once
// Auto-generated by scripts/version_bump.py — do not edit by hand.
// Regenerated on every PlatformIO build.

#define FW_VERSION_MAJOR  1
#define FW_VERSION_MINOR  3
#define FW_VERSION_BUILD  79
#define FW_VERSION_STRING "1.3.79"
#define FW_BUILD_DATE     "2026-05-19 18:11:18"

// Backwards-compatibility aliases for existing consumers in main.cpp.
#define FIRMWARE_VERSION  FW_VERSION_STRING
#define BUILD_NUMBER      FW_VERSION_BUILD
#define BUILD_GIT         "45284f7"
